<a href="https://colab.research.google.com/github/Utree/deeplearning2_colab_log/blob/master/4%E7%AB%A0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Word2vecの高速化

前章で実装したCBOWモデルの問題点
-> 大きなコーパスを扱うと、処理に大きな負荷がかかる

ボトルネック
- 入力層のone-hot表現と重みの行列の積による計算
- 中間層と重み行列の積
- Softmaxレイヤの計算

行列の積を計算する際、計算リソースが必要になってしまう

そこで、Embeddingレイヤを導入する

前章のword2vecの実装では、MatMulレイヤを使って、行列の積を計算することにより、行列の特定の行を抜き出していました。

しかし、これでは計算リソースを大量に使ってしまい非効率。
そこで、配列のインデックスを指定することによって、抽出の処理を書くことにします。

単語IDに該当する行を抜き出し、単語の密なベクトル表現(word embedding, distributed representation)を得ることから、Embeddingレイヤと名付けます

「中間層と重みの行列の積、Softmaxレイヤの計算」の解決方法として、Negative samplingという手法をとります。

キーとなるアイデアは「多値分類」を「二値分類」で近似することです。

中間層と出力側の重み行列の積は正解の単語IDに対応する列だけを抽出し、
出力したベクトルと中間層のニューロンとの内積を計算する
結果、出力層のニューロンは１つだけになる

上記を実装することにより、「多値分類」から「二値分類」に変換することができますが、

正例の学習を行なったに過ぎず間違った答えに関しては、学習できていません。
そこで、譜例に対してはSigmoidレイヤの出力を0に近づける必要があります。
しかし、すべての間違った答えに対して、学習(計算)を行うと、時間がかかってしまいます。

そこで、数個ピックアップ(サンプリング)を行い、学習を行います。

負例のサンプリング方法に関して、

単語の出現頻度から正規分布を求め、コーパス内でよく使われる単語は抽出されやすくし、あまり使われない単語は抽出されにくくする。

**得られた単語の分散表現を評価する**

man:woman = king : ?
のような類推問題を解き、単語ベクトルの空間上での関係性を示すことで評価する

**転移学習** ... ある分野で学んだ知識を別の分野に適応させる

word2vecで得られた単語の分散表現は、炊事単語を求める用途に利用できるだけではない。

- 大きなコーパスで学習を行い、個別のタスクで利用する

  例えば、テキスト分類や文書クラスタリング、品詞タグ付け、感情表分析など
  
- 単語をベクトル変換するように、文章をを固定長のベクトルに変換することができる

In [0]:
import numpy as np
W = np.arange(21).reshape(7, 3)
W

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [0]:
W[2]

array([6, 7, 8])

In [0]:
W[5]

array([15, 16, 17])

In [0]:
idx = np.array([1, 0, 3, 0])
W[idx]

array([[ 3,  4,  5],
       [ 0,  1,  2],
       [ 9, 10, 11],
       [ 0,  1,  2]])

In [0]:
class Embedding:
  def __init__(self, W):
    self.params = [W]
    self.grads = [np.zeros_like(W)]
    self.idx = None
    
  def forward(self, idx):
    W, = self.params
    self.idx = idx
    out = W[idx]
    return out
  
  def backward(self, dout):
    dW, = self.grads
    dW[...] = 0
    dW[self.idx] = dout
    return None

In [0]:
class EmbeddingDot:
  def __init__(self, W):
    self.embed = Embedding(W)
    self.params = self.embed.params
    self.grads = self.embed.grads
    self.cache = None
    
  def forward(self, h, idx):
    target_W = self.embed.forward(idx)
    out = np.sum(target_W * h, axis=1)
    
    self.cache = (h, target_W)
    return out
  
  def backward(self, dout):
    h, target_W = self.cache
    dout = dout.reshape(dout.shape[0], 1)
    
    dtarget_W = dout * h
    self.embed.backward(dtarget_W)
    dh = dout * target_W
    return dh

In [0]:
import numpy as np

In [0]:
# 0から9の数字の中からひとつの数字をランダムにサンプリング
np.random.choice(10)

2

In [0]:
np.random.choice(10)

0

In [0]:
# words からひとつだけランダムにサンプリング
words = ['you', 'say', 'goodbye', 'I', 'hello', '.']
np.random.choice(words)

'I'

In [0]:
# 5つだけランダムサンプリング(重複あり)
np.random.choice(words, size=5)

array(['hello', 'goodbye', '.', 'hello', '.'], dtype='<U7')

In [0]:
# 5つだけランダムサンプリング(重複なし)
np.random.choice(words, size=5, replace=False)

array(['say', 'hello', 'goodbye', 'you', 'I'], dtype='<U7')

In [0]:
# 確率分布に従ってサンプリング
p = [0.5, 0.1, 0.05, 0.2, 0.05, 0.1]
np.random.choice(words, p=p)

'I'

In [0]:
p = [0.7, 0.29, 0.01]
new_p = np.power(p, 0.75)
new_p /= np.sum(new_p)
print(new_p)

[0.64196878 0.33150408 0.02652714]


In [0]:
import numpy as np

In [0]:
# softmax関数
def softmax(x):
  if x.ndim == 2:
    x = x - x.max(axis=1, keepdims=True)
    x = np.exp(x)
    x /= x.sum(axis=1, keepdims=True)
  elif x.ndim == 1:
    x = x - np.max(x)
    x = np.exp(x) / np.sum(np.exp(x))
    
  return x

# 交差エントロピー誤差関数
def cross_entropy_error(y, t):
  if y.ndim == 1:
    t = t.reshape(1, t.size)
    y = y.reshape(1, t.size)
    
  # 教師データがone-hot-vectorの場合、正解ラベルのインデックスに変換
  if t.size == y.size:
    t = t.argmax(axis=1)
    
  batch_size = y.shape[0]
  
  return -np.sum(np.log(y[np.arange(batch_size), t] + 1e-7)) / batch_size

In [0]:
# Embeddingレイヤ
class Embedding:
  def __init__(self, W):
    self.params = [W]
    self.grads = [np.zeros_like(W)]
    self.idx = None
    
  def forward(self, idx):
    W, = self.params
    self.idx = idx
    out = W[idx]
    return out
  
  def backward(self, dout):
    dW, = self.grads
    dW[...] = 0
    np.add.at(dW, self.idx, dout)
    return None
# SigmoidWithLossレイヤ
class SigmoidWithLoss:
  def __init__(self):
    self.params, self.grads = [], []
    self.loss = None
    self.y =None # sigmoidの出力
    self.t = None # 教師データ
    
  def forward(self, x, t):
    self.t = t
    self.y = 1 / (1 + np.exp(-x))
    
    self.loss = cross_entropy_error(np.c_[1 - self.y, self.y], self.t)
    
    return self.loss
  
  def backward(self, dout=1):
    batch_size = self.t.shape[0]
    
    dx = (self.y - self.t) * dout / batch_size
    return dx

In [0]:
import collections
GPU = True

In [0]:
# UnigramSampler
class UnigramSampler:
  def __init__(self, corpus, power, sample_size):
    self.sample_size = sample_size
    self.vocab_size = None
    self.word_p = None
    
    counts = collections.Counter()
    for word_id in corpus:
      counts[word_id] += 1
      
    vocab_size = len(counts)
    self.vocab_size = vocab_size
    
    self.word_p = np.zeros(vocab_size)
    for i in range(vocab_size):
      self.word_p[i] = counts[i]
      
    self.word_p = np.power(self.word_p, power)
    self.word_p /= np.sum(self.word_p)
    
  def get_negative_sample(self, target):
    batch_size = target.shape[0]
    
    if not GPU:
      negative_sample = np.zeros((batch_size, self.sample_size), dtype=np.int32)

      for i in range(batch_size):
        p = self.word_p.copy()
        target_idx = target[i]
        p[target_idx] = 0
        p /= p.sum()
        negative_sample[i, :] = np.random.choice(self.vocab_size,  size=self.sample_size, replace=False, p=p)
    else:
      # GPU(cupy)で計算するときは、速度を優先
      # 負例にターゲットが含まれるケースがある
      negative_sample = np.random.choice(self.vocab_size, size=(batch_size, self.sample_size), replace=True, p=self.word_p)
      
    return negative_sample

In [0]:
corpus = np.array([0, 1, 2, 3, 4, 1, 2, 3])
power = 0.75
sample_size = 2

sampler = UnigramSampler(corpus, power, sample_size)
target = np.array([1, 3, 0])
negative_sample = sampler.get_negative_sample(target)
print(negative_sample)

[[2 2]
 [1 4]
 [0 4]]


In [0]:
class NegativeSamplingLoss:
  def __init__(self, W, corpus, power=0.75, sample_size=5):
    self.sample_size = sample_size
    self.sampler = UnigramSampler(corpus, power, sample_size)
    self.loss_layers = [SigmoidWithLoss() for _ in range(sample_size + 1)]
    self.embed_dot_layers = [EmbeddingDot(W) for _ in range(sample_size + 1)]
    
    self.params, self.grads = [], []
    for layer in self.embed_dot_layers:
      self.params += layer.params
      self.grads += layer.grads
      
  def forward(self, h, target):
    batch_size = target.shape[0]
    negative_sample = self.sampler.get_negative_sample(target)
    
    # 正例のフォワード
    score = self.embed_dot_layers[0].forward(h, target)
    correct_label = np.ones(batch_size, dtype=np.int32)
    loss = self.loss_layers[0].forward(score, correct_label)
    
    # 負例のフォワード
    negative_label = np.zeros(batch_size, dtype=np.int32)
    for i in range(self.sample_size):
      negative_target = negative_sample[:, i]
      score = self.embed_dot_layers[1 + i].forward(h, negative_target)
      loss += self.loss_layers[1 + i].forward(score, negative_label)
      
    return loss
  
  def backward(self, dout=1):
    dh = 0
    for l0, l1 in zip(self.loss_layers, self.embed_dot_layers):
      dscore = l0.backward(dout)
      dh += l1.backward(dscore)
      
    return dh

In [0]:
class CBOW:
  def __init__(self, vocab_size, hidden_size, window_size, corpus):
    V, H = vocab_size, hidden_size
    
    # 重みの初期化
    W_in = 0.01 * np.random.randn(V, H).astype('f')
    W_out = 0.01 * np.random.randn(V, H).astype('f')
    
    # レイヤの生成
    self.in_layers = []
    for i in range(2 * window_size):
      layer = Embedding(W_in) # Embeddingレイヤを使用
      self.in_layers.append(layer)
    self.ns_loss = NegativeSamplingLoss(W_out, corpus, power=0.75, sample_size=5)
    
    # すべての重みと勾配をリストにまとめる
    layers = self.in_layers + [self.ns_loss]
    self.params, self.grads = [], []
    for layer in layers:
      self.params += layer.params
      self.grads += layer.grads
      
    # メンバ変数に単語の分散表現を設定
    self.word_vecs = W_in
    
  def forward(self, contexts, target):
    h = 0
    for i, layer in enumerate(self.in_layers):
      h += layer.forward(contexts[:, i])
    h *= 1 / len(self.in_layers)
    loss = self.ns_loss.forward(h, target)
    return loss
  
  def backward(self, dout=1):
    dout = self.ns_loss.backward(dout)
    dout *= 1 / len(self.in_layers)
    for layer in self.in_layers:
      layer.backward(dout)
    return None

In [0]:
import numpy as np
GPU = True
import pickle

In [0]:
def clip_grads(grads, max_norm):
  total_norm = 0
  for grad in grads:
    total_norm += np.sum(grad ** 2)
  total_norm = np.sqrt(total_norm)
  
  rate = max_norm / (total_norm + 1e-6)
  if rate < 1:
    for grad in grads:
      grad *= rate

In [0]:
import numpy
import time
import matplotlib.pyplot as plt
import numpy as np

In [0]:
def remove_duplicate(params, grads):
  '''
  パラメータ配列中の重複する重みを一つに集約し、
  その重みに対応する勾配を加算する
  '''
  params, grads = params[:], grads[:] # copy list
  
  while True:
    find_flg = False
    L = len(params)
    
    for i in range(0, L - 1):
      for j in range(i + 1, L):
        # 重みを共有する場合
        if params[i] is params[j]:
          grads[i] += grads[j] # 勾配の可算
          find_flg = True
          params.pop(j)
          grads.pop(j)
        # 転置行列として重みを共有する場合(weight tying)
        elif params[i].ndim == 2 and params[j].ndim == 2 and \
        params[i].T.shape == params[j].shape and np.all(params[i].T == params[j]):
          grads[i] += grads[j].T
          find_flg = True
          params.pop(j)
          grads.pop(j)
        
        if find_flg: break
      if find_flg: break
        
    if not find_flg: break
      
  return params, grads

In [0]:
class Trainer:
  def __init__(self, model, optimizer):
    self.model = model
    self.optimizer = optimizer
    self.loss_list = []
    self.eval_iterval = None
    self.current_epoch = 0
    
  def fit(self, x, t, max_epoch=10, batch_size=32, max_grad=None, eval_interval=20):
    data_size = len(x)
    max_iters = data_size // batch_size
    self.eval_interval = eval_interval
    model, optimizer = self.model, self.optimizer
    total_loss = 0
    loss_count = 0
    
    start_time = time.time()
    for epoch in range(max_epoch):
      # シャッフル
      idx = numpy.random.permutation(numpy.arange(data_size))
      x = x[idx]
      t = t[idx]
      
      for iters in range(max_iters):
        batch_x = x[iters*batch_size:(iters+1)*batch_size]
        batch_t = t[iters*batch_size:(iters+1)*batch_size]
        
        # 勾配を求め、パラメータを更新
        loss = model.forward(batch_x, batch_t)
        model.backward()
        params, grads = remove_duplicate(model.params, model.grads) # 共有された重みを１つに集約
        if max_grad is not None:
          clip_grads(grads, max_grad)
        optimizer.update(params, grads)
        total_loss += loss
        loss_count += 1
        
        # 評価
        if(eval_interval is not None) and (iters % eval_interval) == 0:
          avg_loss = total_loss / loss_count
          elapsed_time = time.time() - start_time
          print('| epoch %d | iter %d / %d | time %d[s] | loss %.2f'
               % (self.current_epoch + 1, iters + 1, max_iters, elapsed_time, avg_loss))
          self.loss_list.append(float(avg_loss))
          total_loss, loss_count = 0, 0
      
      self.current_epoch += 1
    
  def plot(self, ylim=None):
    x = numpy.arange(len(self.loss_list))
    if ylim is not None:
      plt.ylim(*ylim)
    plt.plot(x, self.loss_list, label='train')
    plt.xlabel('iterations (x' + str(self.eval_interval) + ')')
    plt.ylabel('loss')
    plt.show()

In [0]:
class Adam:
  '''
  Adam
  '''
  def __init__(self, lr=0.001, beta1=0.9, beta2=0.99):
    self.lr = lr
    self.beta1 = beta1
    self.beta2 = beta2
    self.iter = 0
    self.m = None
    self.v = None
    
  def update(self, params, grads):
    if self.m is None:
      self.m, self.v = [], []
      for param in params:
        self.m.append(np.zeros_like(param))
        self.v.append(np.zeros_like(param))
        
    self.iter += 1
    lr_t = self.lr * np.sqrt(1.0 - self.beta2**self.iter) / (1.0 - self.beta1**self.iter)
    
    for i in range(len(params)):
      self.m[i] += (1 - self.beta1) * (grads[i] - self.m[i])
      self.v[i] += (1 - self.beta2) * (grads[i]**2 - self.v[i])
      
      params[i] -= lr_t * self.m[i] / (np.sqrt(self.v[i]) + 1e-7)

In [0]:
def create_contexts_target(corpus, window_size=1):
  '''
  コンテキストとターゲットの作成
  
  :param corpus: コーパス(単語IDのリスト)
  :param window_size: ウィンドウサイズ(ウィンドウサイズが1のときは、単語の左右1単語がコンテキスト)
  :return:
  '''
  target = corpus[window_size:-window_size]
  contexts = []
  
  for idx in range(window_size, len(corpus)-window_size):
    cs = []
    for t in range(-window_size, window_size + 1):
      if t == 0:
        continue
      cs.append(corpus[idx + t])
    contexts.append(cs)
    
  return np.array(contexts), np.array(target)

def to_cpu(x):
  import numpy
  if type(x) == numpy.ndarray:
    return x
  return np.asnumpy(x)

def to_gpu(x):
  import cupy
  if type(x) == cupy.ndarray:
    return x
  return cupy.asarray(x)

In [0]:
# coding: utf-8
import sys
import os
sys.path.append('..')
try:
    import urllib.request
except ImportError:
    raise ImportError('Use Python3!')
import pickle
import numpy as np


url_base = 'https://raw.githubusercontent.com/tomsercu/lstm/master/data/'
key_file = {
    'train':'ptb.train.txt',
    'test':'ptb.test.txt',
    'valid':'ptb.valid.txt'
}
save_file = {
    'train':'ptb.train.npy',
    'test':'ptb.test.npy',
    'valid':'ptb.valid.npy'
}
vocab_file = 'ptb.vocab.pkl'

dataset_dir = os.path.dirname(os.path.abspath("__file__"))


def _download(file_name):
    file_path = dataset_dir + '/' + file_name
    if os.path.exists(file_path):
        return

    print('Downloading ' + file_name + ' ... ')

    try:
        urllib.request.urlretrieve(url_base + file_name, file_path)
    except urllib.error.URLError:
        import ssl
        ssl._create_default_https_context = ssl._create_unverified_context
        urllib.request.urlretrieve(url_base + file_name, file_path)

    print('Done')


def load_vocab():
    vocab_path = dataset_dir + '/' + vocab_file

    if os.path.exists(vocab_path):
        with open(vocab_path, 'rb') as f:
            word_to_id, id_to_word = pickle.load(f)
        return word_to_id, id_to_word

    word_to_id = {}
    id_to_word = {}
    data_type = 'train'
    file_name = key_file[data_type]
    file_path = dataset_dir + '/' + file_name

    _download(file_name)

    words = open(file_path).read().replace('\n', '<eos>').strip().split()

    for i, word in enumerate(words):
        if word not in word_to_id:
            tmp_id = len(word_to_id)
            word_to_id[word] = tmp_id
            id_to_word[tmp_id] = word

    with open(vocab_path, 'wb') as f:
        pickle.dump((word_to_id, id_to_word), f)

    return word_to_id, id_to_word


def load_data(data_type='train'):
    '''
        :param data_type: データの種類：'train' or 'test' or 'valid (val)'
        :return:
    '''
    if data_type == 'val': data_type = 'valid'
    save_path = dataset_dir + '/' + save_file[data_type]

    word_to_id, id_to_word = load_vocab()

    if os.path.exists(save_path):
        corpus = np.load(save_path)
        return corpus, word_to_id, id_to_word

    file_name = key_file[data_type]
    file_path = dataset_dir + '/' + file_name
    _download(file_name)

    words = open(file_path).read().replace('\n', '<eos>').strip().split()
    corpus = np.array([word_to_id[w] for w in words])

    np.save(save_path, corpus)
    return corpus, word_to_id, id_to_word


if __name__ == '__main__':
    for data_type in ('train', 'val', 'test'):
        load_data(data_type)


In [0]:
!ls

ptb.test.npy  ptb.train.npy  ptb.valid.npy  ptb.vocab.pkl
ptb.test.txt  ptb.train.txt  ptb.valid.txt  sample_data


In [0]:
# ハイパーパラメータ
window_size = 5
hidden_size = 100
batch_size = 100
max_epoch = 10

# データの読み込み
corpus, word_to_id, id_to_word = load_data('train')
vocab_size = len(word_to_id)

contexts, target = create_contexts_target(corpus, window_size)
if GPU:
  contexts, target = to_gpu(contexts), to_gpu(target)

# モデルなどの生成
model = CBOW(vocab_size, hidden_size, window_size, corpus)
optimizer = Adam()
trainer = Trainer(model, optimizer)

# 学習開始
trainer.fit(contexts, target, max_epoch, batch_size)
trainer.plot()

# 後ほど利用できるように、必要なデータを保存
word_vecs = model.word_vecs

if GPU:
  word_vecs = to_cpu(word_vecs)
params = {}
params['word_vecs'] = word_vecs.astype(np.float16)
params['word_to_id'] = word_to_id
params['id_to_word'] = id_to_word
pkl_file = 'cbow_params.pkl'
with open(pkl_file, 'wb') as f:
  pickle.dump(params, f, -1)

ValueError: ignored